#ifndef _ACTIVE_SESSION_HPP
#define _ACTIVE_SESSION_HPP

#define SESSION_COMMAND_KEEP_ALIVE 1
#define SESSION_COMMAND_TEXT_MESSAGE 2
#define SESSION_COMMAND_DELIVER_MESSAGE 3
#define SESSION_COMMAND_LIST_USERS 4
#define SESSION_COMMAND_GET_MESSAGES 5

#define SESSION_RESPONSE_OK 200
#define SESSION_RESPONSE_ERROR 100
#define SESSION_RESPONSE_ERROR_INVALID_USER 101
#define SESSION_RESPONSE_ERROR_MESSAGE_TOO_SHORT 102
#define SESSION_RESPONSE_ERROR_CONNECTION_LOST 103

#endif
