#ifndef _GATE_PARSER_HPP
#define _GATE_PARSER_HPP

#define GATE_MESSAGE_HEADER_ACCEPT 0
#define GATE_MESSAGE_HEADER_REJECT 1
#define GATE_MESSAGE_HEADER_REJECT_INVALID_DESTINATION_USER 2
#define GATE_MESSAGE_HEADER_REJECT_INVALID_DESTINATION_KEY 3
#define GATE_MESSAGE_HEADER_REJECT_INVALID_HEADER 4
#define GATE_MESSAGE_HEADER_REJECT_MESSAGE_TOO_BIG 5
#define GATE_MESSAGE_HEADER_REJECT_SENDER_BANNED 6
#define GATE_MESSAGE_HEADER_REJECT_SENDER_KEY_BANNED 7
#define GATE_MESSAGE_HEADER_REJECT_EXISTS 8

// Not from protocol specification, only for implementation internal usage.
#define GATE_MESSAGE_HEADER_REJECT_SILENTBLOCK 100

#define GATE_MESSAGE_BODY_ACCEPT 0
#define GATE_MESSAGE_BODY_REJECT 1
#define GATE_MESSAGE_BODY_REJECT_INVALID_SIZE 2

#endif
