#ifndef _SOCKET_NAME_HPP
#define _SOCKET_NAME_HPP

#define TALKD_SOCKET_NAME "talkd.socket"

#define OK 200

#define ERROR 100
#define ERROR_UNKNOWN_COMMAND 101
#define ERROR_TOO_SHORT 102
#define ERROR_INVALID_SIZE 103
#define ERROR_INVALID_USER 104
#define ERROR_USER_EXISTS 105
#define ERROR_INVALID_IP 106

#define COMMAND_SHUTDOWN 1
#define COMMAND_GET_PUBLIC_KEY 2
#define COMMAND_ADD_USER 3
#define COMMAND_REMOVE_USER 4
#define COMMAND_LIST_USERS 5
#define COMMAND_LIST_BANNED_IP 6
#define COMMAND_BAN_IP 7
#define COMMAND_UNBAN_IP 8

#endif
