#ifndef _CRYPTO_DEFINITIONS_HPP
#define _CRYPTO_DEFINITIONS_HPP

namespace Crypto::X25519
{
	enum Constants
	{
		SCHEME_ID = 0,
		SYMMETRIC_KEY_ID = 0,
		PRIVATE_KEY_ID = 1,
		PUBLIC_KEY_ID = 2,
		SIGNATURE_PRIVATE_KEY_ID = 3,
		SIGNATURE_PUBLIC_KEY_ID = 4,

		KEY_SIZE = 32,
		SIGNATURE_PRIVATE_KEY_SIZE = 64,
		SIGNATURE_PUBLIC_KEY_SIZE = 32,
		SIGNATURE_SIZE = 64,
		NONCE_SIZE = 24,
		MAC_SIZE = 16,
		SALT_SIZE = 16,
		CRYPTO_HEADER_SIZE = MAC_SIZE + NONCE_SIZE
	};
}

#endif
