#ifndef _CRYPTO_DEFINITIONS_HPP
#define _CRYPTO_DEFINITIONS_HPP

#define KEY_SIZE 32
#define SIGNATURE_PRIVATE_KEY_SIZE 64
#define SIGNATURE_PUBLIC_KEY_SIZE 32
#define SIGNATURE_SIZE 64
#define NONCE_SIZE 24
#define MAC_SIZE 16
#define SALT_SIZE 16

#endif
